name: jkd
on:
  workflow_dispatch:
  schedule:
     - cron: '*/20 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JKD_COOKIE: ${{ secrets.JKD_COOKIE }}
        JKD_USER_AGENT: ${{ secrets.JKD_USER_AGENT }}
        JKD_WITHDRAW: ${{ secrets.JKD_WITHDRAW }}
        JKD_FAKE_IOS: ${{ secrets.JKD_FAKE_IOS }}
        JKD_NOTIFY: ${{ secrets.JKD_NOTIFY }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: 'Run jkd'
        if: env.JKD_COOKIE
        run: |
          node jkd.js
