# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: xp

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1-15/1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER }}
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        XP_live: ${{ secrets.XP_live }}
        XP_CASH: ${{ secrets.XP_CASH }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye66666/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          npm install
      - name: 'RUN xp1 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp2 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp3 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp4 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp5 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp6 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp7 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp8 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp9 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
      - name: 'RUN xp10 '
        if: env.XP_iboxpayHEADER
        run: |
          cd ~/JavaScript
          node Task/iboxpay.js
          
#       - name: 'RUN [xp] '
#         if: env.XP_iboxpayHEADER
#         run: |
#           cd ~/JavaScript
#           for i in {1..10}
#           do
#               echo $i
#               node Task/iboxpay.js
#           done
#         env:
          
#           PUSH_KEY: ${{ secrets.PUSH_KEY }}
#           BARK_PUSH: ${{ secrets.BARK_PUSH }}
#           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
#           TG_USER_ID: ${{ secrets.TG_USER_ID }}
#           BARK_SOUND: ${{ secrets.BARK_SOUND }}
#           DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
#           DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
